### PR TITLE
[#174991105] Upgrade passport-saml dependency to v1.3.5

### PR DESCRIPTION
**Pull request by BurnedMarshal**
Upgrade `passport-saml` dependecy to `v1.3.5`

### CODE REVIEW

**Comment by pp-ps** [comment]
Do we still need to clone the strategy?
https://github.com/node-saml/passport-saml/commit/ffbd2f61e05e8c6e932422fb4f54523b15c106df

**Comment by BurnedMarshal** [comment]
> Do we still need to clone the strategy?
> [node-saml/passport-saml@ffbd2f6](https://github.com/node-saml/passport-saml/commit/ffbd2f61e05e8c6e932422fb4f54523b15c106df)

We don't use the MultisamlStrategy, the implementation extends the SamlStrategy. we cannot use `MultisamlStrategy` because we need the CustomSamlClient for `preValidateResponse` e `tamperAuthorizeRequest`.

**Review by gunzip — APPROVED** [review]
if this is tested locally it can be merged

**Comment by BurnedMarshal** [comment]
> if this is tested locally it can be merged

@gunzip local test was successful. I've added a little description inside README in 47b463d

**Review by balanza — APPROVED** [review]

**Comment by balanza** [comment]
@BurnedMarshal can we merge?

**Pull request merged**
